=== stetro/DBW/prak1/src/src/main/resources/definitions/employees.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="employees">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee" maxOccurs="unbounded" type="employee"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="employee">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="department" type="department"/>
            <xs:element name="payment" type="price"/>
            <xs:element name="hometown" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="department">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="leading" type="xs:boolean" default="false"/>
                <xs:attribute name="id" type="xs:int"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="price">
        <xs:simpleContent>
            <xs:extension base="xs:float">
                <xs:attribute name="current" type="currenttype"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="currenttype">
        <xs:restriction base="xs:string">
            <xs:enumeration value="euro"/>
            <xs:enumeration value="dollar"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== stetro/DBW/prak1/src/src/main/resources/definitions/employees.xml
<?xml version="1.0" encoding="UTF-8"?>

<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="employees.xsd">
    <employee id="12">
        <name>Steffen Tr√∂ster</name>
        <department id="23" leading="false" name="Softwareentwicklung"></department>
    </employee>
    <employee id="13">
        <name>Bernd Schneider</name>
        <department id="24" leading="true" name="Management"></department>
    </employee>
    <employee id="14">
        <name>Michael Schmidt</name>
        <department id="23" leading="false" name="Softwareentwicklung"></department>
    </employee>
    <employee id="15">
        <name>Joachim Friedrich</name>
        <department id="23" leading="true" name="Softwareentwicklung"></department>
    </employee>
</employees>
