=== stetro/DBW/prak1/src/src/main/resources/definitions/products.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="products">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="product" maxOccurs="unbounded" type="product">
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="product">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="buildtime" type="buildtime"/>
            <xs:element name="price" type="europrice"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int"/>
    </xs:complexType>

    <xs:simpleType name="buildtime">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{2}:[0-9]{2}:[0-9]{2}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="europrice">
        <xs:restriction base="xs:string">
            <xs:pattern value="[.0-9]{1,20}.[0-9]{2} â‚¬"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== stetro/DBW/prak1/src/src/main/resources/definitions/products.xml
<?xml version="1.0" encoding="UTF-8"?>
<products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="products.xsd">
    <product id="0">
        <name>Staubmax 250</name>
        <buildtime>07:45:34</buildtime>
        <price>12.50 €</price>
    </product>
    <product id="1">
        <name>Staubmax 230i</name>
        <buildtime>07:05:34</buildtime>
        <price>14.50 €</price>
    </product>
    <product id="2">
        <name>Behälter Reiniger</name>
        <buildtime>03:56:12</buildtime>
        <price>3.43 €</price>
    </product>
    <product id="3">
        <name>Sauger Filter</name>
        <buildtime>00:34:23</buildtime>
        <price>5.59 €</price>
    </product>
</products>
