=== stetro/DBW/prak2/src/src/main/resources/definitions/companies.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="companies">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="company" maxOccurs="unbounded" type="company"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="company">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="contact" type="contact"/>
            <xs:element name="address" type="address"/>
            <xs:element name="types" type="companyTypes"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int"/>
    </xs:complexType>


    <xs:complexType name="contact">
        <xs:sequence>
            <xs:element name="phone" type="xs:string"/>
            <xs:element name="fax" type="xs:string"/>
            <xs:element name="person" type="xs:string"/>
            <xs:element name="web" type="xs:anyURI"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="address">
        <xs:sequence>
            <xs:element name="street" type="xs:string"/>
            <xs:element name="city" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="companyTypes">
        <xs:sequence>
            <xs:element name="type" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== stetro/DBW/prak2/src/src/main/resources/definitions/companies.xml
<?xml version="1.0" encoding="UTF-8"?>
<companies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="companies.xsd">
    <company>
        <name>Loma Drehteile GmbH &amp; Co KG</name>
        <contact>
            <phone>+49 7429 9303-0</phone>
            <fax>+49 7429 9303-10</fax>
            <person>Frau Rosa Dreher</person>
            <web>http://www.loma-drehteile.com</web>
        </contact>
        <address>
            <street>Eichenstrasse 10</street>
            <city>D-78598 KÃ¶nigsheim</city>
        </address>
        <types>
            <type>Hersteller</type>
        </types>
    </company>
</companies>
